### ISSUE TITLE
Compatability with BungeePerms

### ISSUE THREAD

**Issue by scungilli** [DawnFire-Realms/CommunityBridge#231]
First of all, this is an incredible plugin and it does exactly what it's supposed to do! It works very well with Xenforo and PermissionsEX. 

However, it would be highly beneficial to many server owners if the developers would consider adding a BungeePerms permission handler in the CommunityBridge.jar file. Having the community bridge plugin working across an entire grouping of bungee-servers on a single machine would be very helpful

Here is the permissions plugin: http://www.spigotmc.org/resources/bungeeperms.25/

There are actually three separate plugins that go along with BungeePerms. There is the BungeeCord plugin, the bukkit plugin, and then the bungee-bukkit bridge plugin. All three of the jar files can be found in the zip in the link below.

http://www.wea-ondara.net/webcontent/dev/release/2.1.2/BungeePerms-2.1.2.tar.gz

Thanks for any help and consideration!

-scungilli

**Comment by scungilli** [comment]
BungeePerms has vault compatability but Community Bridge doesn't seem to hook properly. Here is the error message I get:

[14:14:05] [pool-3-thread-24/WARN]: Exception in thread "pool-3-thread-24" 
[14:14:05] [pool-3-thread-24/WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 223
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:457)
	at net.alpenblock.bungeeperms.platform.bukkit.bridge.bridges.vault.Permission_BungeePerms.getPlayerGroups(Permission_BungeePerms.java:285)
	at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:684)
	at org.communitybridge.permissionhandlers.PermissionHandlerVault.getGroups(PermissionHandlerVault.java:37)
	at org.communitybridge.groupsynchronizer.PlayerGroupState.generate(PlayerGroupState.java:49)
	at org.communitybridge.main.WebApplication.synchronizeGroups(WebApplication.java:363)
	at org.communitybridge.main.WebApplication.synchronizePlayer(WebApplication.java:280)
	at org.communitybridge.main.WebApplication.access$1(WebApplication.java:273)
	at org.communitybridge.main.WebApplication$1.run(WebApplication.java:235)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

**Comment by xion87** [comment]
Please add Support on it...
