### ISSUE TITLE
lags and Server Errors

### ISSUE THREAD

**Issue by K475u** [DawnFire-Realms/CommunityBridge#232]
02:06:07] [Craft Scheduler Thread - 78/WARN]: Exception in thread "Craft Scheduler Thread - 78" 
[02:06:07] [Craft Scheduler Thread - 78/WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 65
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString(Unknown Source)
	at org.communitybridge.bansynchronizer.BanSynchronizer.banPlayerGame(BanSynchronizer.java:71)
	at org.communitybridge.bansynchronizer.BanSynchronizer.synchronizeWebToGame(BanSynchronizer.java:248)
	at org.communitybridge.bansynchronizer.BanSynchronizer.synchronize(BanSynchronizer.java:43)
	at org.communitybridge.main.WebApplication.synchronizeAll(WebApplication.java:268)
	at org.communitybridge.main.CommunityBridge$2.run(CommunityBridge.java:235)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

anyone ?!

**Comment by exmex** [comment]
Don't enable bans on both sides.

The ban system is just stupid. It doesn't work because it saves UUID's and tries to read UUID's out of the database
