### ISSUE TITLE
Error on player join and quit (group from XenForo not pulling across into Minecraft)

### ISSUE THREAD

**Issue by Pawned** [DawnFire-Realms/CommunityBridge#241]
Hello,

Currently having an issue with the latest build of CommunityBridge on Minecraft 1.8.1 using Spigot.

The plugin seems to be unable to obtain the group that the player is in on XenForo and thus throws a null pointer exception when trying to synchronize them. No errors are shown when the plugin is loaded however it does say `[CommunityBridge] Invalid storage method for secondary groups, disabling secondary synchronization.` despite secondary groups being disabled in the config. But the main error happens when a player joins or leaves the server:

`[13:46:47] [Craft Scheduler Thread - 254/WARN]: Exception in thread "Craft Scheduler Thread - 254" 
[13:46:47] [Craft Scheduler Thread - 254/WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 110817
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.communitybridge.main.WebApplication.getUserPrimaryGroupID(WebApplication.java:167)
	at org.communitybridge.groupsynchronizer.PlayerGroupState.generate(PlayerGroupState.java:47)
	at org.communitybridge.main.WebApplication.synchronizeGroups(WebApplication.java:363)
	at org.communitybridge.main.WebApplication.synchronizePlayer(WebApplication.java:280)
	at org.communitybridge.main.WebApplication.access$1(WebApplication.java:273)
	at org.communitybridge.main.WebApplication$1.run(WebApplication.java:235)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

The plugin detects fine if you're registered on the forum, providing the correct text when you login if you are or are not registered so it is having no problem linking the user to the forum account, it just seems to fail at syncing the group.

I've double-checked the config to make sure the group column is correct but maybe I am missing something, so here's a pastebin of my config (passwords removed): http://pastebin.com/bN9KL6EH

Appreciate any help you can provide.

**Comment by Pawned** [comment]
Issue has been resolved by setting secondary storage-method to single. Unsure why this has an affect since secondary is turned off, but happy to report the problem is now solved.
