### ISSUE TITLE
Issues with spigot 1.10.2

### ISSUE THREAD

**Issue by poblabs** [DawnFire-Realms/CommunityBridge#252]
The plugin works for the most part - but I am getting a lot of errors with auto-remind and whatever this is below. It occurs every 10 mins

Any chance this will be upgraded? Or is this a dead project?

```
[12:27:35 WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 59
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.communitybridge.main.WebApplication.synchronizeAll(WebApplication.java:258)
        at org.communitybridge.main.CommunityBridge$2.run(CommunityBridge.java:235)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

```

**Comment by tcatlas** [comment]
Second this.

```
[14:54:23] [Craft Scheduler Thread - 1337/INFO]: [CommunityBridge] Running player synchronization.
[14:54:23] [Craft Scheduler Thread - 1337/WARN]: Exception in thread "Craft Scheduler Thread - 1337" 
[14:54:23] [Craft Scheduler Thread - 1337/WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 1549
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at org.communitybridge.main.WebApplication.synchronizeAll(WebApplication.java:258)
    at org.communitybridge.main.CommunityBridge$2.run(CommunityBridge.java:235)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[15:03:23] [Craft Scheduler Thread - 1347/INFO]: [Metrics] Unexpected end of file from server
[15:04:23] [Craft Scheduler Thread - 1347/WARN]: Exception in thread "Craft Scheduler Thread - 1347" 
[15:04:23] [Craft Scheduler Thread - 1347/WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 1548
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at org.communitybridge.main.CBMetrics.postPlugin(CBMetrics.java:350)
    at org.communitybridge.main.CBMetrics.access$4(CBMetrics.java:343)
    at org.communitybridge.main.CBMetrics$1.run(CBMetrics.java:229)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[15:13:08] [Craft Scheduler Thread - 1362/INFO]: [Metrics] Connection reset
[15:14:23] [Craft Scheduler Thread - 1364/INFO]: [CommunityBridge] Running player synchronization.
[15:14:23] [Craft Scheduler Thread - 1364/WARN]: Exception in thread "Craft Scheduler Thread - 1364" 
[15:14:23] [Craft Scheduler Thread - 1364/WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 1549
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at org.communitybridge.main.WebApplication.synchronizeAll(WebApplication.java:258)
    at org.communitybridge.main.CommunityBridge$2.run(CommunityBridge.java:235)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[15:19:23] [Craft Scheduler Thread - 1365/WARN]: Exception in thread "Craft Scheduler Thread - 1365" 
[15:19:23] [Craft Scheduler Thread - 1365/WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 1548
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at org.communitybridge.main.CBMetrics.postPlugin(CBMetrics.java:350)
    at org.communitybridge.main.CBMetrics.access$4(CBMetrics.java:343)
    at org.communitybridge.main.CBMetrics$1.run(CBMetrics.java:229)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
```

**Comment by xorinzor** [comment]
Well it says it's still only for 1.8, 1.10 (or somewhere along the way) must have had an API update because one of the methods CommunityBridge is trying to use, no longer exists. That's the error you're getting.

**Comment by poblabs** [comment]
Dead project.
